In [2]:
import torch

inputs = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
outputs = torch.tensor([[0], [1], [1], [0]], dtype=torch.float)

num_hidden_units = 2
learning_rate = 0.02

model = torch.nn.Sequential(
    torch.nn.Linear(inputs.shape[1], num_hidden_units),
    torch.nn.Tanh(),
    torch.nn.Linear(num_hidden_units, 1),
    torch.nn.Tanh()
)

loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for i in range(10000):
  # forward
  output = model(inputs)

  # loss
  loss = loss_fn(output, outputs)
  if i % 1000 == 0:
    print(loss)

  # backward, optim
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

# should be 0, 1, 1, 0
print(output)

tensor(1.6909, grad_fn=<MseLossBackward0>)
tensor(0.2474, grad_fn=<MseLossBackward0>)
tensor(0.2351, grad_fn=<MseLossBackward0>)
tensor(0.1114, grad_fn=<MseLossBackward0>)
tensor(0.0125, grad_fn=<MseLossBackward0>)
tensor(0.0041, grad_fn=<MseLossBackward0>)
tensor(0.0023, grad_fn=<MseLossBackward0>)
tensor(0.0015, grad_fn=<MseLossBackward0>)
tensor(0.0011, grad_fn=<MseLossBackward0>)
tensor(0.0009, grad_fn=<MseLossBackward0>)
tensor([[0.0026],
        [0.9624],
        [0.9625],
        [0.0035]], grad_fn=<TanhBackward0>)


In [3]:
# Print weights and biases
print(list(model.parameters()))


[Parameter containing:
tensor([[ 1.8039,  1.7786],
        [-1.3617, -1.3501]], requires_grad=True), Parameter containing:
tensor([-0.5564,  2.0651], requires_grad=True), Parameter containing:
tensor([[1.9758, 1.9274]], requires_grad=True), Parameter containing:
tensor([-0.8655], requires_grad=True)]
